title: 3D LED science display with Scratch
hero_image: images/banner.png
description: Make a 3D LED science display with Scratch on the Raspberry Pi
listed: false
copyedit: false
last_tested: "2021-03-03"
steps:
  - title: Introduction
  - title: Get inspiration
  - title: Choose you model
  - title: Build your model
  - title: Control your LEDs
  - title: Add graphics and sound
  - title: Share your project
  - title: Reflect
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: What next?
