---
title: 3D LED science display with Scratch
hero_image: images/banner.png
description: Make a 3D LED science display with Scratch on the Raspberry Pi
meta_title: Raspberry Pi Projects | Scratch | 3D LED
meta_description: The fourth Raspberry Pi project in the Physical computing with Scratch path. Use your new skills to make a 3D LED science display. 
listed: true
copyedit: true
last_tested: '2021-03-03'
steps:
  - title: What you will make
  - title: Design your model
    completion:
      - engaged
  - title: Build your model
  - title: Control your LEDs
    completion:
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Challenge